name: ayat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # time
  timer_builder: ^2.0.0
  adhan: ^1.0.0
  geolocator: ^9.0.1
  permission_handler: ^10.0.0
  syncfusion_flutter_datepicker: ^20.2.40
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git
  flutter_audio_query: ^0.3.5+6
  audio_manager: ^0.8.2
  google_mobile_ads: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.5
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - data/
     - quran/1/
     - quran/2/
     - quran/3/
     - quran/4/
     - quran/5/
     - quran/6/
     - quran/7/
     - quran/8/
     - quran/9/
     - quran/10/
     - quran/11/
     - quran/12/
     - quran/13/
     - quran/14/
     - quran/15/
     - quran/16/
     - quran/17/
     - quran/18/
     - quran/19/
     - quran/20/
     - quran/21/
     - quran/22/
     - quran/23/
     - quran/24/
     - quran/25/
     - quran/26/
     - quran/27/
     - quran/28/
     - quran/29/
     - quran/30/
     - quran/31/
     - quran/32/
     - quran/33/
     - quran/34/
     - quran/35/
     - quran/36/
     - quran/37/
     - quran/38/
     - quran/39/
     - quran/40/
     - quran/41/
     - quran/42/
     - quran/43/
     - quran/44/
     - quran/45/
     - quran/46/
     - quran/47/
     - quran/48/
     - quran/49/
     - quran/50/
     - quran/51/
     - quran/52/
     - quran/53/
     - quran/54/
     - quran/55/
     - quran/56/
     - quran/57/
     - quran/58/
     - quran/59/
     - quran/60/
     - quran/61/
     - quran/62/
     - quran/63/
     - quran/64/
     - quran/65/
     - quran/66/
     - quran/67/
     - quran/68/
     - quran/69/
     - quran/70/
     - quran/71/
     - quran/72/
     - quran/73/
     - quran/74/
     - quran/75/
     - quran/76/
     - quran/77/
     - quran/78/
     - quran/79/
     - quran/80/
     - quran/81/
     - quran/82/
     - quran/83/
     - quran/84/
     - quran/85/
     - quran/86/
     - quran/87/
     - quran/88/
     - quran/89/
     - quran/90/
     - quran/91/
     - quran/92/
     - quran/93/
     - quran/94/
     - quran/95/
     - quran/96/
     - quran/97/
     - quran/98/
     - quran/99/
     - quran/100/
     - quran/101/
     - quran/102/
     - quran/103/
     - quran/104/
     - quran/105/
     - quran/106/
     - quran/107/
     - quran/108/
     - quran/109/
     - quran/110/
     - quran/111/
     - quran/112/
     - quran/113/
     - quran/114/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#ffffff"